# exec(open('test_encoder.py', 'r').read(), globals())
# exec(open('test_motor.py', 'r').read(), globals())
# exec(open('test_servo.py', 'r').read(), globals())
# exec(open('test_cloud_platform.py', 'r').read(), globals())
exec(open('test_go_straight.py', 'r').read(), globals())
